### ISSUE TITLE
Update clang-format version in readme

### ISSUE THREAD

**Issue by ksuszka** [davetcoleman/roscpp_code_format#11]
This readme is linked from official ROS documentation as a go-to way of maintaining code style for ROS. However, instruction in readme is outdated, it seems that package clang-format-3.8 is no longer available in Ubuntu 18.04 repository. Please update the instruction.

**Comment by davetcoleman** [comment]
@ksuszka hopefully https://github.com/davetcoleman/roscpp_code_format/pull/13 addressed your issue. Any additional PRs to improve this repo are welcome!
