### ISSUE TITLE
No break before opening braces of function definition.

### ISSUE THREAD

**Issue by BennyRe** [davetcoleman/roscpp_code_format#2]
```
int main()
{
}
```

gets formated to

```
int main() {}
```

This should be covered by `BreakBeforeBraces: Allman` but somehow it doesn't work. Tried other options here but I had no success.

**Comment by davetcoleman** [comment]
Agreed, violates:

> Braces, both open and close, go on their own lines (no "cuddled braces").

I think there are small bugs in clang but overall clang is very helpful. A newer version of clang might fix this, but when I tried upgrading other things changed that broke the format even more. Overall, this hasn't been a big issue for me because I try to never have empty functions.

**Comment by BennyRe** [comment]
I used this empty main because it's the smallest working sample. It cudddles my braces also for non-empty functions.

**Comment by davetcoleman** [comment]
Do you know of a better tool than clang for making code obey ROS format?

**Comment by BennyRe** [comment]
This is the config I use for eclipse. Didn't verify it completely againt the style guide. (Remove the .txt postfix)
[ROS.xml](https://github.com/davetcoleman/roscpp_code_format/files/55121/ROS.xml.txt)

[Uncrustify](http://uncrustify.sourceforge.net/) also looks promising. It has Atom and Emacs integration.

**Comment by davetcoleman** [comment]
I just fixed this bug: https://github.com/davetcoleman/roscpp_code_format/commit/9ae3e9c9d68e45583b1f140c46ea7543cf08a32e

I think I'll stick to clang-format, its used widely as well.
